### ISSUE TITLE
Issue with HTML files on Mac

### ISSUE THREAD

**Issue by zuzanu** [orbisius/orbisius-wp-media-protector#3]
Hi,
I need to protect all files in a custom directory. In this directory are images, JavaScript, and HTML files. That's why I changed the path in the .htaccess file and in the check_file() function.
I also deactivate the preg_match() function inside the check_file() function .
It is working except on a Mac. Here the Chrome browser downloads the HTML file instead of opening it.

What can be the problem?

Thank you
Sergiu Chiriac

**Comment by lordspace** [comment]
yes, the script offers the file for download.
if you need to output you will need to comment out everything after file_exists check up until fopen

**Comment by lordspace** [comment]
if you need us to troubleshoot or customize something. No problem, however, this is a paid service https://orbisius.com/contact/quick-contact

**Comment by zuzanu** [comment]
I find another way to fix this. It hasn't anything to do with Mac or Chrome, rather with the user rights.  
An administrator has all the rights so it's working. A subscriber can only read posts. When I grant raw_html rights to the subscriber role I don't know why but it's working.
I use the Members Plugin to alter the user rights.

Thank you,
Sergiu Chiriac

**Comment by lordspace** [comment]
cool
