### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by szynol** [orbisius/orbisius-wp-media-protector#6]
Hi,
I have done all with your instruction, and works perfectly.... maybe too perfectly :) All images on site (eg logo in png format) are not visible when you are not logged. When i log in - i see everything. Can you help me?

Adress: https://farmacja.hr

**Comment by lordspace** [comment]
Hahahah 😄  Too perfectly. That's funny.
You may need to add one more line that will exclude the logo.
I see that you've closed the ticket.
Can you paste your solution so it can help others?

**Comment by szynol** [comment]
Sure. I have added to htaccess :

RewriteCond %{REQUEST_URI} !\.jpg [NC]
  RewriteCond %{REQUEST_URI} !\.png [NC]

I needed only restriction for pdf, docx etc.

Kind regards
Paweł

pon., 20 sie 2018, 17:25 użytkownik Svetoslav Marinov <
notifications@github.com> napisał:

**Comment by lordspace** [comment]
oh, ok. Thanks for sharing
